name: flutter_map_mbtiles_provider
description: MBTilesProvider was originally implemented as part of flutter_map package
version: 0.1.0
repository: https://github.com/DonWasyl/flutter_map_mbtiles_provider

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  path_provider: ^2.0.14
  sqflite: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: